[package]
name = "qt-cb"
version = "0.1.0"
edition = "2021"

[dependencies]
cpp_core = "0.6.0"
qt_widgets = "0.5.0"
qt_core = "0.5.0"

[build-dependencies]
cc = {version = "1", features = ["parallel"] }

[dev-dependencies]
cpp_core = "0.6.0"
qt_gui = "0.5.0"
qt_widgets = "0.5.0"
