/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct QLineEdit {
    _unused: [u8; 0],
}
extern "C" {
    pub fn QLineEdit_onTextChanged(
        s: *mut QLineEdit,
        arg1: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut QLineEdit,
                arg2: *mut ::std::os::raw::c_void,
                arg3: *mut ::std::os::raw::c_void,
            ),
        >,
        data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn QLineEdit_onReturnPressed(
        s: *mut QLineEdit,
        arg1: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut QLineEdit, arg2: *mut ::std::os::raw::c_void),
        >,
        data: *mut ::std::os::raw::c_void,
    );
}
